version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/test/app
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/stop-dev.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start-dev.sh
      timeout: 60
      runas: ubuntu