server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mariadb://localhost:3306/copro
    username: root
    password: chlrldnd3533
    driver-class-name: org.mariadb.jdbc.Driver