server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mariadb://localhost:3307/copro
    username: root
    password: 990621
    driver-class-name: org.mariadb.jdbc.Driver
